feat: Checks if question or challenge is in any of learners courses
Clean-CaDET/platform pull request #46
Opened 2021-05-08 15:59 UTC by VladimirBudjen

2021-05-20 17:16 UTC, VladimirBudjen commented on SmartTutorTests/Integration/SubmissionTests.cs
> +
I will delete this line in next commit. 😄

2021-05-21 06:02 UTC, Luburic requested changes
A few minor things to address, including the CodeFactor tip.

2021-05-21 06:02 UTC, Luburic commented on SmartTutorTests/Unit/SubmissionTests.cs
> +        private static readonly Submission Submission = new Submission(1, 1, true, DateTime.Now);
Remove this. Submission should be an abstract class as it does not make sense as a standalone object (submission of what?). As a side note, we should avoid sharing state between tests, even when it's immutable - if this test suite grows and more tests start to depend on this shared field, what happens when one test changes it?

Why do you need these fields in the test data? If it turns out we don't, don't forget to remove the additional parameter you added to the QuestionSubmission constructor, and the two constructors you added to Submission.

2021-05-21 06:02 UTC, Luburic commented on SmartTutor/ProgressModel/Submissions/Submission.cs
> +            Id = id;
Look at my comment in the SubmissionTests class, then come back here.

2021-05-24 05:27 UTC, Luburic approved these changes
Looks good.

2021-05-24 05:27 UTC, merged