Keycloak role mapping.
Clean-CaDET/platform pull request #68
Opened 2021-07-27 10:36 UTC by lukaDoric

This is the POC of how the user (in this case Learner) registration would look with IAM (in this case Keycloak) integrated in Smart-tutor. There are also some changes marked with TODO that will be done after merging #67 and #62 in master.

2021-07-28 04:04 UTC, Luburic requested changes
Some minor changes required, mostly names and packaging. Comments inline.

2021-07-28 04:04 UTC, Luburic commented on SmartTutor/SmartTutor.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
Why do we need this dependency? System.Text.Json should be quite enough, and I'm not a fan of introducing libraries when the base framework can provide all the functionality.

In general we should minimize additional code brought into our platform as that can cause issues with licensing. This is not the case for this particular package, but once again the base framework support should be enough.

2021-07-28 04:04 UTC, Luburic commented on SmartTutorTests/Integration/LearnerTests.cs
> +                scope.ServiceProvider.GetRequiredService<IKeycloakService>());
An example where we can inject the "NoAuthProvider" instead of the "KeycloakAuthProvider"

2021-07-28 04:04 UTC, Luburic commented on SmartTutor/Keycloak/KeycloakService.cs
> +      public class KeycloakService : IKeycloakService
KeycloakAuthProvider

2021-07-28 04:04 UTC, Luburic commented on SmartTutor/Keycloak/KeycloakService.cs
> +}
We should discuss this class on our next call.

2021-07-29 14:47 UTC, Luburic approved these changes
Looks good. Once you add the docker secret support you can merge.

2021-08-13 12:54 UTC, lukaDoric commented
The GetSecret method was exported to the Util class so it could be available in other classes as well. @DanijelRadakovic @Luburic

2021-08-14 10:07 UTC, DanijelRadakovic approved these changes

2021-08-30 11:05 UTC, Luburic approved these changes

2021-08-30 11:06 UTC, Luburic commented
@lukaDoric Could you resolve conflict and merge?

2021-08-31 12:22 UTC, merged